[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[functions]
  external_node_modules = ["stripe"]

[build.environment]
  NODE_VERSION = "16"
  GO_VERSION = "1.18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200